// <auto-generated />
using EFAutomapperBugRepro;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EFAutomapperBugRepro.Migrations
{
    [DbContext(typeof(ReproContext))]
    [Migration("20180703143509_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.0-rtm-30799")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("EFAutomapperBugRepro.Thing", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.Property<int>("TypeId");

                    b.HasKey("Id");

                    b.HasIndex("TypeId");

                    b.ToTable("Things");

                    b.HasData(
                        new { Id = 1, Name = "Thing 1", TypeId = 1 },
                        new { Id = 2, Name = "Thing 2", TypeId = 2 }
                    );
                });

            modelBuilder.Entity("EFAutomapperBugRepro.ThingType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("ThingTypes");

                    b.HasData(
                        new { Id = 1, Name = "Thing type 1" },
                        new { Id = 2, Name = "Thing type 2" }
                    );
                });

            modelBuilder.Entity("EFAutomapperBugRepro.Thing", b =>
                {
                    b.HasOne("EFAutomapperBugRepro.ThingType", "Type")
                        .WithMany()
                        .HasForeignKey("TypeId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
